### ISSUE TITLE
Failed to load the keyboard-localization package

### ISSUE THREAD

**Issue by PointedEars** [andischerer/atom-keyboard-localization#109]
1. Start Atom

**Atom Version**: 1.5.3
**System**: Debian GNU/Linux
**Thrown From**: [keyboard-localization](https://github.com/andischerer/atom-keyboard-localization) package, v1.4.15
### Stack Trace

Failed to load the keyboard-localization package

```
At Cannot find module 'fs-plus'

Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:336:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:286:25)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/atom/packages/keyboard-localization/lib/keymap-loader.coffee:2:6)
    at Object.<anonymous> (/usr/local/atom/packages/keyboard-localization/lib/keymap-loader.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/usr/local/atom/packages/keyboard-localization/lib/keyboard-localization.coffee:2:16)
    at Object.<anonymous> (/usr/local/atom/packages/keyboard-localization/lib/keyboard-localization.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Module.require (module.js:365:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:720:27)
    at /usr/share/atom/resources/app.asar/src/package.js:116:28
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at Package.module.exports.Package.load (/usr/share/atom/resources/app.asar/src/package.js:106:12)
    at PackageManager.module.exports.PackageManager.loadPackage (/usr/share/atom/resources/app.asar/src/package-manager.js:445:14)
    at PackageManager.module.exports.PackageManager.loadPackages (/usr/share/atom/resources/app.asar/src/package-manager.js:395:14)
    at AtomEnvironment.module.exports.AtomEnvironment.startEditorWindow (/usr/share/atom/resources/app.asar/src/atom-environment.js:684:21)
    at module.exports (/usr/share/atom/resources/app.asar/src/initialize-application-window.js:28:10)
    at setupWindow (file:///usr/share/atom/resources/app.asar/static/index.js:86:5)
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "customFileTypes": {
      "source.ini": [
        ".buckconfig",
        ".flowconfig"
      ],
      "source.json": [
        ".arcconfig"
      ],
      "source.python": [
        "BUCK"
      ]
    },
    "disabledPackages": [
      "tree-view",
      "es-navigation",
      "git-grep"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-htmltidy, v2.3.0
atom-ternjs, v0.13.2
atomatigit, v1.5.5
auto-detect-indentation, v0.4.2
autoclose-html, v0.22.0
autocomplete-awk, v0.1.2
autocomplete-bibtex, v0.6.2
autocomplete-html-entities, v0.1.0
autocomplete-paths, v1.0.2
autocomplete-php, v0.3.7
autocomplete-python, v1.6.1
autocomplete-xml, v0.8.2
autoupdate-packages, v1.3.1
branch-status, v0.8.1
character-table, v0.4.3
clipboard-plus, v0.5.1
color-picker, v2.1.1
column-select, v0.2.0
compare-files, v0.6.2
css-snippets, v0.9.0
ctrl-last-tab, v0.3.0
docblockr, v0.7.3
emmet, v2.4.1
emmet-snippets-compatibility, v1.0.4
file-icons, v1.6.15
filesize, v0.4.2
git-diff-details, v0.23.0
git-go, v1.0.1
git-hide, v0.1.2
git-log, v0.4.1
git-tabs, v0.3.0
highlight-selected, v0.11.2
hyperclick-php, v0.2.1
javascript-snippets, v1.2.1
js-hyperclick, v1.4.1
js-refactor, v0.6.0
keyboard-localization, v1.4.15
latex, v0.29.0
latexer, v0.3.0
line-count-status, v0.0.3
line-jumper, v0.14.1
linter, v1.11.3
linter-checkbashisms, v0.1.5
linter-chktex, v1.2.5
linter-csslint, v1.3.1
linter-htmlhint, v1.0.3
linter-jshint, v2.0.2
linter-less, v2.4.2
linter-mixed-indent, v1.1.0
linter-php, v1.2.0
linter-pylint, v1.2.0
linter-shellcheck, v1.1.0
linter-xmllint, v1.3.4
local-history, v3.2.3
method-separator, v0.1.4
minimap, v4.19.0
minimap-cursorline, v0.1.0
minimap-find-and-replace, v4.4.0
minimap-git-diff, v4.1.8
minimap-hide, v0.3.0
minimap-highlight-selected, v4.3.1
minimap-linter, v1.1.1
minimap-pigments, v0.1.7
nav-panel, v0.0.11
navigate, v0.1.13
navigate-indent, v0.1.0
nuclide, v0.118.0
open-recent, v5.0.0
php-debug, v0.2.2
php-extract-method, v0.2.1
php-getters-setters, v0.5.5
pigments, v0.24.1
project-view, v0.5.0
punchclock, v0.6.5
python-isort, v0.0.7
python-tools, v0.6.7
recent-projects, v0.9.5
refactor, v0.6.0
remember-file-positions, v0.2.2
remote-edit, v1.8.24
revert-buffer, v0.5.0
svn, v0.0.9
symbols-tree-view, v0.11.0
text-manipulation, v0.6.0
tree-view-git-branch, v0.0.6
tree-view-git-status, v0.2.3
up2date, v0.1.2
vim-mode-clipboard-plus, v0.2.0
vim-mode-plus, v0.21.3
w3c-validation, v0.4.0
xkcd-comics, v0.3.0
xml-tools, v0.2.1

# Dev
No dev packages
```

**Comment by elestedt** [comment]
Same issue on Windows, same version of Atom and atom-keyboard-localixation

**Comment by andischerer** [comment]
Have you tried installing the package via apm command on commandline ?

```
apm install keyboard-localization
```

**Comment by elestedt** [comment]
I am behind a corporate proxy and atom does not support setting proxy on Windows that I've found - much less NTLM authentication...

**Comment by hristian-carabulea** [comment]
Hello, Andi. Thank you so much for the keyboard package you created. 

I also had problems installing it following the instructions at https://github.com/andischerer/atom-keyboard-localization. 

After a few installs and uninstalls and downloads, etc. :-), I finally found this entry. And I can confirm that this command worked OK:

apm install keyboard-localization

When you have the chance, perhaps you could change the Installation directions in the README.md  at the link I mentioned above. 

Thank you.
