### ISSUE TITLE
Failed to activate the keyboard-localization package

### ISSUE THREAD

**Issue by mauricioklein** [andischerer/atom-keyboard-localization#134]
[Enter steps to reproduce below:]
1. Update package;
2. Restart Atom;

**Atom Version**: 1.8.0
**System**: Ubuntu 16.04
**Thrown From**: [keyboard-localization](https://github.com/andischerer/atom-keyboard-localization) package, v1.4.18
### Stack Trace

Failed to activate the keyboard-localization package

```
At Cannot find module 'fs-plus'

Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:338:15)
    at Function.Module._resolveFilename (/usr/share/atom/resources/app.asar/src/module-cache.js:383:52)
    at Function.Module._load (module.js:289:25)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/klein/.atom/packages/keyboard-localization/lib/keymap-loader.coffee:2:6)
    at Object.<anonymous> (/home/klein/.atom/packages/keyboard-localization/lib/keymap-loader.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Object.<anonymous> (/home/klein/.atom/packages/keyboard-localization/lib/keyboard-localization.coffee:2:16)
    at Object.<anonymous> (/home/klein/.atom/packages/keyboard-localization/lib/keyboard-localization.coffee:1:1)
    at Module._compile (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:103:30)
    at Object.defineProperty.value [as .coffee] (/usr/share/atom/resources/app.asar/src/compile-cache.js:208:21)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:313:12)
    at Module.require (module.js:366:17)
    at require (/usr/share/atom/resources/app.asar/src/native-compile-cache.js:50:27)
    at Package.module.exports.Package.requireMainModule (/usr/share/atom/resources/app.asar/src/package.js:715:27)
    at Package.module.exports.Package.activateNow (/usr/share/atom/resources/app.asar/src/package.js:173:16)
    at /usr/share/atom/resources/app.asar/src/package.js:156:32
    at Package.module.exports.Package.measure (/usr/share/atom/resources/app.asar/src/package.js:92:15)
    at /usr/share/atom/resources/app.asar/src/package.js:149:26
    at Package.module.exports.Package.activate (/usr/share/atom/resources/app.asar/src/package.js:146:34)
    at PackageManager.module.exports.PackageManager.activatePackage (/usr/share/atom/resources/app.asar/src/package-manager.js:538:21)
    at /usr/share/atom/resources/app.asar/src/package-manager.js:519:29
    at Config.module.exports.Config.transactAsync (/usr/share/atom/resources/app.asar/src/config.js:337:18)
    at PackageManager.module.exports.PackageManager.activatePackages (/usr/share/atom/resources/app.asar/src/package-manager.js:514:19)
    at PackageManager.module.exports.PackageManager.activate (/usr/share/atom/resources/app.asar/src/package-manager.js:497:46)
    at /usr/share/atom/resources/app.asar/src/atom-environment.js:754:28
```
### Commands

```
```
### Config

``` json
{
  "core": {
    "audioBeep": false,
    "disabledPackages": [
      "autosave"
    ],
    "themes": [
      "isotope-ui",
      "one-dark-syntax"
    ]
  },
  "keyboard-localization": {
    "useKeyboardLayout": "fr_FR"
  }
}
```
### Installed Packages

``` coffee
# User
atom-erb, v0.2.0
autoclose-html, v0.23.0
keyboard-localization, v1.4.18
remember-folds, v0.1.0
ruby-block, v0.3.5
single-click-open, v0.2.1

# Dev
No dev packages
```

**Comment by andischerer** [comment]
This package has been deprecated.
See [details](https://github.com/andischerer/atom-keyboard-localization/blob/master/README.md)
