### ISSUE TITLE
install on windows

### ISSUE THREAD

**Issue by christophfroehlich** [andischerer/atom-keyboard-localization#22]
Hi!
When I install the package on windows, I get an error during startup

```
Cannot find module 'fs-plus'

Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:328:15)
    at Function.Module._resolveFilename (C:\Users\cfr\AppData\Local\atom\app-0.191.0\resources\app\src\module-cache.js:383:52)
    at Function.Module._load (module.js:270:25)
    at Module.require (module.js:357:17)
    at require (module.js:376:17)
    at Object.<anonymous> (/C:/Users/cfr/github/atom-keyboard-international/lib/key-mapper.coffee:6:8)
    at Object.<anonymous> (/C:/Users/cfr/github/atom-keyboard-international/lib/key-mapper.coffee:123:4)
    at Module._compile (module.js:452:26)
    at Object.requireCoffeeScript (C:\Users\cfr\AppData\Local\atom\app-0.191.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:85:19)
    at Module.load (module.js:347:32)
```

Do I have to install fs-plus? Can I do that only with manually installing Node.js to get npm?

**Comment by andischerer** [comment]
It seems to me that the package install process didnt finish correctly. The fs-plus dependency should resolve automatically. Have you tried to remove the package and reinstall it ?

If that didnt work you could trie to install the package via apm on the commandline:

```
apm install keyboard-localization
```

**Comment by christophfroehlich** [comment]
arr.. Forget everything I wrote ;) I just found your package via an atom-issue thread and I didn't manage to find the package in the package-manager, because I looked only for "atom-keyboard-localization".. So I tried to manually install it via github/download, but now everything is fine and it works for me!
