### ISSUE TITLE
Solved - Can't use it (failed to activate error) - 0.182.0 / Win8.1

### ISSUE THREAD

**Issue by steschner** [andischerer/atom-keyboard-localization#6]
Unfortunately this doesn't work for me since I get this error in the console

```
Failed to activate package named 'atom-keyboard-localization' Error: Cannot find module 'fs-plus'
    at Module._resolveFilename (module.js:351:15)
    at Function.Module._resolveFilename (C:\Users\ekwinoks\AppData\Local\atom\app-0.182.0\resources\app\src\module-cache.js:383:52)
    at Function.Module._load (module.js:293:25)
    at Module.require (module.js:380:17)
    at require (module.js:399:17)
    at Object.<anonymous> (/C:/Users/ekwinoks/.atom/packages/atom-keyboard-localization/lib/key-mapper.coffee:6:8)
    at Object.<anonymous> (/C:/Users/ekwinoks/.atom/packages/atom-keyboard-localization/lib/key-mapper.coffee:101:4)
    at Module._compile (module.js:475:26)
    at Object.requireCoffeeScript (C:\Users\ekwinoks\AppData\Local\atom\app-0.182.0\resources\app\node_modules\coffee-cash\lib\coffee-cash.js:67:19)
    at Module.load (module.js:370:32)
```

I've tried to install the missing fs-plus but couldn't get it to work. Am I running some kind of special configuration or why hasn't anyone else got this error? I am not sure what to do now.

Thanks for your help in advance!

**Comment by steschner** [comment]
Now it works and I don't know why. Sorry to bother you. Can be closed.

**Comment by andischerer** [comment]
no problem
