### ISSUE TITLE
Uncaught TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by jcwdb** [andischerer/atom-keyboard-localization#65]
[Enter steps to reproduce below:]
1. I tried to solve my French keyboard not working with Atom. Braces and brackets are faulty and fold lines instead of typing. 
2. Installed keyboard-localizaiton, restarted Atom, and tried to keymaps, generated this exception.

**Atom Version**: 1.0.13
**System**: WINDOWS 10
**Thrown From**: [keyboard-localization](https://github.com/andischerer/atom-keyboard-localization) package, v1.4.8
### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of undefined

```
At /C:/Users/Jonathan/.atom/packages/keyboard-localization/lib/helpers.coffee:13

TypeError: Cannot read property 'indexOf' of undefined
  at exports.charCodeFromKeyIdentifier (C:\Users\Jonathan\.atom\packages\keyboard-localization\lib\helpers.coffee:8:52)
  at KeyEventView.module.exports.KeyEventView.setKey (C:\Users\Jonathan\.atom\packages\keyboard-localization\lib\views\key-event-view.coffee:29:19)
  at KeymapGeneratorView.module.exports.KeymapGeneratorView.onKeyDown (C:\Users\Jonathan\.atom\packages\keyboard-localization\lib\views\keymap-generator-view.coffee:89:18)
  at HTMLInputElement.<anonymous> (C:\Users\Jonathan\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\atom-space-pen-views\node_modules\space-pen\lib\space-pen.js:220:36)
  at HTMLInputElement.jQuery.event.dispatch (C:\Users\Jonathan\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\jquery\dist\jquery.js:4435:9)
  at HTMLInputElement.elemData.handle (C:\Users\Jonathan\AppData\Local\atom\app-1.0.13\resources\app.asar\node_modules\jquery\dist\jquery.js:4121:28)

```
### Commands

```
     -0:59.1.0 keyboard-localization:keymap-generator (atom-text-editor.editor.is-focused)
  3x -0:45.6.0 pane:increase-size (atom-pane.pane.active)
```
### Config

``` json
{
  "core": {}
}
```
### Installed Packages

``` coffee
# User
keyboard-localization, v1.4.8
minimap, v4.13.3

# Dev
No dev packages
```

**Comment by benavern** [comment]
My french keyboard map is solved for the same problems you had, but now I cant comment (ctrl+/) I wanted to create the shortcut and had the same issue...

is there something to do for that ?

**Comment by ricardomatias** [comment]
+1 on Linux

**Comment by rmebjesus** [comment]
Exactly the same problems as the OP though my layout is Portuguese. Running Linux here.

**Comment by radarsu** [comment]
+1 Windows 7

**Comment by dotnetCarpenter** [comment]
Got the same error message - not sure it is the same issue though.
[Enter steps to reproduce below:]
1. Press Ctrl
2. Error message pop-up in the top right.
   ![keyboard-localication-package](https://cloud.githubusercontent.com/assets/43763/10942005/54f71198-830e-11e5-8fc3-8be044ce50bf.png)

**Atom Version**: 1.1.0
**System**: Microsoft Windows 7 Professional 
**Thrown From**: [keyboard-localization](https://github.com/andischerer/atom-keyboard-localization) package, v1.4.10

### Stack Trace

Uncaught TypeError: Cannot read property 'indexOf' of undefined

```
At C:\Users\dotnet\.atom\packages\keyboard-localization\lib\helpers.coffee:12

TypeError: Cannot read property 'indexOf' of undefined
  at exports.charCodeFromKeyIdentifier (C:\Users\dotnet\.atom\packages\keyboard-localization\lib\helpers.coffee:7:9)
  at KeyMapper.translateKeyBinding (C:\Users\dotnet\.atom\packages\keyboard-localization\lib\key-mapper.coffee:24:8)
  at KeyMapper.remap (C:\Users\dotnet\.atom\packages\keyboard-localization\lib\key-mapper.coffee:42:37)
  at Object.KeyboardLocalization.onKeyDown (C:\Users\dotnet\.atom\packages\keyboard-localization\lib\keyboard-localization.coffee:121:18)
  at KeymapManager.keystrokeForKeyboardEvent (C:\Users\dotnet\.atom\packages\keyboard-localization\lib\keyboard-localization.coffee:63:13)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (C:\Users\dotnet\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\atom-keymap\lib\keymap-manager.js:313:24)
  at HTMLDocument.module.exports.WindowEventHandler.handleDocumentKeydown (C:\Users\dotnet\AppData\Local\atom\app-1.1.0\resources\app.asar\src\window-event-handler.js:97:20)

```

### Commands

```
```

### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "atom-dark-syntax"
    ],
    "projectHome": "C:\\Users\\dotnet\\Projects",
    "disabledPackages": [
      "language-batch",
      "emmet-simplified",
      "emmet"
    ]
  },
  "keyboard-localization": {
    "useKeyboardLayout": "da_DK"
  }
}
```

### Installed Packages

``` coffee
# User
editorconfig, v1.2.2
keyboard-localization, v1.4.10
language-batchfile, v0.4.0
language-ejs, v0.2.0

# Dev
No dev packages
```
