### ISSUE TITLE
Uncaught TypeError: Cannot redefine property: keyIdentifier

### ISSUE THREAD

**Issue by elalaouifaris** [andischerer/atom-keyboard-localization#79]
[Enter steps to reproduce below:]
1. using a French keyboard: numbers are accessed using shift + key (not having a number pad on a laptop)
2. to jump 2 words in vi (2w)  ==> need to use Shift + key to get 2. The error occurs at this point. 

**Atom Version**: 1.1.0
**System**: Ubuntu 14.04.3
**Thrown From**: [keyboard-localization](https://github.com/andischerer/atom-keyboard-localization) package, v1.4.10
### Stack Trace

Uncaught TypeError: Cannot redefine property: keyIdentifier

```
At /home/farishouda/.atom/packages/keyboard-localization/lib/key-mapper.coffee:36

TypeError: Cannot redefine property: keyIdentifier
  at Function.defineProperty (native)
  at KeyMapper.translateKeyBinding (/home/farishouda/.atom/packages/keyboard-localization/lib/key-mapper.coffee:36:14)
  at KeyMapper.remap (/home/farishouda/.atom/packages/keyboard-localization/lib/key-mapper.coffee:51:6)
  at Object.KeyboardLocalization.onKeyDown (/home/farishouda/.atom/packages/keyboard-localization/lib/keyboard-localization.coffee:112:19)
  at KeymapManager.keystrokeForKeyboardEvent (/home/farishouda/.atom/packages/keyboard-localization/lib/keyboard-localization.coffee:93:10)
  at VimState.module.exports.VimState.repeatPrefix (/home/farishouda/.atom/packages/vim-mode/lib/vim-state.coffee:590:33)
  at atom-text-editor.registerCommands.repeat-prefix (/home/farishouda/.atom/packages/vim-mode/lib/vim-state.coffee:71:32)
  at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/usr/share/atom/resources/app.asar/src/command-registry.js:243:29)
  at /usr/share/atom/resources/app.asar/src/command-registry.js:3:61
  at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:528:16)
  at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/usr/share/atom/resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:351:22)
  at HTMLDocument.module.exports.WindowEventHandler.handleDocumentKeydown (/usr/share/atom/resources/app.asar/src/window-event-handler.js:97:20)

```
### Commands

```
     -2:05.8.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -2:04.6.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -2:04.5.0 vim-mode:insert-below-with-newline (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -1:49.9.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -1:49.7.0 vim-mode:undo (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -1:46.8.0 vim-mode:insert-below-with-newline (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -1:12.7.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:56.1.0 core:move-right (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:39.1.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:37 vim-mode:move-down (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:20.5.0 vim-mode:move-to-first-character-of-line (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:19.1.0 snippets:next-tab-stop (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:19.1.0 snippets:expand (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:19.1.0 editor:indent (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:02.2.0 vim-mode:repeat-prefix (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
     -0:01.8.0 vim-mode:move-to-next-word (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
```
### Config

``` json
{
  "core": {},
  "keyboard-localization": {
    "useKeyboardLayout": "fr_FR"
  }
}
```
### Installed Packages

``` coffee
# User
atom-django, v0.3.0
ex-mode, v0.7.0
keyboard-localization, v1.4.10
language-r, v0.4.0
vim-mode, v0.63.0

# Dev
No dev packages
```

**Comment by andischerer** [comment]
Should be fixed in v1.4.13. 
If not, feel free to reopen the issue.
